app:
  name: user-backend
  configMap: ["develop-user-backend-map"]
  secretRef: ["develop-user-backend-secret", "develop-aws-secret", "develop-db-secret", "develop-payment-secret", "develop-newrelic"]

image:
  repository: 404523165609.dkr.ecr.us-east-1.amazonaws.com/user-backend
  pullPolicy: Always
  tag: develop

probe:
  path: []

service:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP

services:
  ingress:
    enabled: false
