app:
  name: user-backend
  configMap: ["production-user-backend-map"]
  secretRef: ["production-user-backend-secret", "production-aws-secret", "production-db-secret", "production-payment-secret", "production-newrelic"]

image:
  repository: 404523165609.dkr.ecr.us-east-1.amazonaws.com/user-backend
  pullPolicy: Always
  tag: production

probe:
  path: []

service:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP

services:
  ingress:
    enabled: false
